const { _electron: electron } = require('playwright')
const { resolve } = require('node:path')
const { mkdirSync, mkdtempSync, rmSync } = require('node:fs')
const assert = require('node:assert/strict')
const root = resolve(__dirname, '..')
const screenshots = resolve(root, 'test-results', 'screenshots')
mkdirSync(screenshots, { recursive: true })

async function run() {
  const env = { ...process.env }
  const profile = mkdtempSync(resolve(root, '.ui-review-'))
  env.AURORA_UI_REVIEW_PROFILE = profile
  delete env.ELECTRON_RUN_AS_NODE
  let application
  try {
    application = await electron.launch({ executablePath: require('electron'), args: [resolve(__dirname, 'ui-review-main.cjs')], cwd: root, env, timeout: 30000 })
    const page = await application.firstWindow()
    await page.getByRole('heading', { name: '现在就听', exact: true }).waitFor()
    const info = await application.evaluate(({ app }) => ({ isolatedProfile: true, version: app.getVersion() }))
    console.log(JSON.stringify({ ...info, build: env.AURORA_UI_REVIEW_PACKAGED === '1' ? 'packaged-asar' : 'production-out' }))
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.screenshot({ path: resolve(screenshots, 'empty-library.png') })
    console.log('EMPTY_UI_READY')
    const library = await application.evaluate(require('./demo-library.cjs'), root)
    console.log(JSON.stringify({ songs: library.songs, covers: library.covers, cached: library.cached }))
    await page.reload()
    await page.getByRole('heading', { name: '为你精选', exact: true }).waitFor()

    async function size(width, height) {
      await application.evaluate(({ BrowserWindow }, dimensions) => BrowserWindow.getAllWindows()[0].setContentSize(...dimensions), [width, height])
      await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
      const actual = await page.evaluate(() => [innerWidth, innerHeight])
      console.log(JSON.stringify({ requested: [width, height], actual }))
    }
    async function shot(name) {
      await page.screenshot({ path: resolve(screenshots, name + '.png'), scale: 'css', animations: 'disabled' })
      const layout = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, mainOverflow: document.querySelector('.main-content').scrollWidth > document.querySelector('.main-content').clientWidth }))
      assert.equal(layout.overflow, false, name + ': document overflow')
      assert.equal(layout.mainOverflow, false, name + ': content overflow')
      const sidebar = await page.evaluate(() => ({ bottom: document.querySelector('.sidebar-bottom').getBoundingClientRect().bottom, playerTop: document.querySelector('.player-bar').getBoundingClientRect().top }))
      assert.ok(sidebar.bottom <= sidebar.playerTop, name + ': sidebar footer hidden behind player')
    }
    for (const [width, height] of [[980, 640], [1320, 860], [1600, 1000]]) { await size(width, height); await shot(`home-light-${width}`) }
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light')
    await page.getByRole('button', { name: '切换明暗主题', exact: true }).click()
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
    await size(1320, 860)
    await shot('home-dark-1320')
    await page.reload()
    await page.getByRole('heading', { name: '为你精选', exact: true }).waitFor()
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
    await page.getByRole('button', { name: '切换明暗主题', exact: true }).click()
    await size(1320, 860)
    await page.getByRole('navigation', { name: '资料库', exact: true }).getByRole('button', { name: '歌曲', exact: true }).click()
    assert.equal(await page.locator('.song-row').count(), 100)
    await page.getByRole('button', { name: '下一页', exact: true }).click()
    assert.match(await page.locator('.pagination').innerText(), /101–125/)
    await shot('library')
    const search = page.getByRole('textbox', { name: '搜索音乐', exact: true })
    await search.fill(library.playable.title)
    await page.locator('.song-row').first().waitFor()
    assert.ok(await page.locator('.song-row').count() > 0)
    await page.screenshot({ path: resolve(screenshots, 'search.png'), scale: 'css' })
    await page.getByRole('slider', { name: '音量', exact: true }).fill('0')
    const playRow = page.locator('.song-row').filter({ has: page.locator('.song-identity b', { hasText: library.playable.title }) }).first()
    await playRow.locator('.song-identity').click()
    await page.waitForFunction(() => navigator.mediaSession?.playbackState === 'playing', null, { timeout: 30000 })
    await page.getByRole('button', { name: '暂停', exact: true }).click()
    await page.getByRole('button', { name: '清除搜索', exact: true }).click()
    await page.getByRole('button', { name: '正在播放与歌词', exact: true }).click()
    await page.getByRole('dialog', { name: '正在播放', exact: true }).waitFor()
    await page.getByRole('button', { name: '时间停在旋律里', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('.lyrics-scroll [aria-current="true"]')?.textContent === '时间停在旋律里')
    await shot('now-playing')
    await size(980, 640)
    await shot('now-playing-980')
    await page.keyboard.press('Escape')
    await size(1320, 860)
    await page.getByRole('button', { name: '播放队列', exact: true }).click()
    await shot('queue')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '关闭队列', exact: true }).waitFor({ state: 'hidden' })
    const wasFavorite = await page.evaluate(async id => Boolean((await window.electronAPI.getSongById(id)).data.isFavorite), library.playable.id)
    await page.getByRole('button', { name: wasFavorite ? '取消喜欢当前歌曲' : '喜欢当前歌曲', exact: true }).click()
    assert.equal(await page.evaluate(async id => Boolean((await window.electronAPI.getSongById(id)).data.isFavorite), library.playable.id), !wasFavorite)
    await page.getByRole('navigation', { name: '资料库', exact: true }).getByRole('button', { name: '专辑', exact: true }).click()
    await page.locator('.collection-grid .cover-button').first().click()
    await page.locator('.collection-detail').waitFor()
    await shot('album-detail')

    await page.getByRole('button', { name: '新建歌单', exact: true }).first().click()
    let dialog = page.getByRole('dialog', { name: '新建歌单', exact: true })
    await dialog.getByLabel('歌单名称', { exact: true }).fill('界面验收歌单')
    await dialog.getByRole('button', { name: '保存歌单', exact: true }).click()
    await page.getByRole('heading', { name: '界面验收歌单', exact: true }).waitFor()
    await shot('playlist-empty')
    await page.getByRole('button', { name: '删除歌单', exact: true }).click()
    await page.getByRole('dialog', { name: '删除这张歌单？' }).getByRole('button', { name: '删除歌单', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })

    // Mock only the paid service boundary. No DeepSeek request is made by this test.
    await application.evaluate(({ ipcMain }, songId) => {
      ipcMain.removeHandler('ai:getConfig')
      ipcMain.handle('ai:getConfig', () => ({ success: true, data: { configured: true, baseUrl: 'https://api.deepseek.com', model: 'deepseek-chat' } }))
      ipcMain.removeHandler('ai:generatePlaylist')
      ipcMain.handle('ai:generatePlaylist', () => ({ success: true, data: { name: '安静的一刻', description: '模拟生成结果，用于检查预览与保存。', songIds: [songId] } }))
    }, library.playable.id)
    await page.reload()
    await page.getByRole('heading', { name: '为你精选', exact: true }).waitFor()
    await page.getByRole('button', { name: '新建歌单', exact: true }).first().click()
    dialog = page.getByRole('dialog', { name: '新建歌单', exact: true })
    await dialog.getByRole('button', { name: '智能歌单', exact: true }).click()
    await dialog.getByLabel('此刻想听什么？', { exact: true }).fill('安静的一刻')
    await dialog.getByRole('button', { name: '生成预览', exact: true }).click()
    await dialog.getByLabel('歌单名称', { exact: true }).waitFor()
    assert.equal(await page.evaluate(async () => (await window.electronAPI.getPlaylists()).data.filter(p => p.name === '安静的一刻').length), 0)
    await shot('ai-playlist-preview')
    await dialog.getByRole('button', { name: '保存歌单', exact: true }).click()
    await page.getByRole('heading', { name: '安静的一刻', exact: true }).waitFor()
    await shot('playlist')
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await shot('settings')
    await size(980, 640)
    await shot('settings-980')
    await page.getByRole('button', { name: '跟随系统', exact: true }).click()
    await page.getByRole('button', { name: '深色', exact: true }).click()
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
    await page.getByRole('button', { name: '明亮', exact: true }).click()
    await page.getByRole('button', { name: '＋ OpenAI 兼容', exact: true }).click()
    await page.getByLabel('模型 ID', { exact: true }).fill('test-model')
    await page.getByRole('heading', { name: 'AI 服务与优先级', exact: true }).scrollIntoViewIfNeeded()
    await shot('api-settings-light')
    await page.getByRole('button', { name: '保存 API 与优先级', exact: true }).click()
    assert.equal((await page.evaluate(async () => (await window.electronAPI.getAiProviders()).data))[0].protocol, 'openai')
    await page.getByRole('button', { name: '清空缓存', exact: true }).click()
    await page.getByRole('dialog', { name: '清空本地缓存？' }).getByRole('button', { name: '取消', exact: true }).click()
    const cached = await page.evaluate(async () => (await window.electronAPI.webdav.getCacheInfo()).data.fileCount)
    assert.equal(cached, library.cached)
    console.log(`UI_REVIEW_PASS: three sizes, ${library.songs}-song pagination, search, local playback, seekable lyrics, favorite persistence, queue, album detail, playlist CRUD, AI preview before save, settings, cache cancellation`)
    if (errors.length) throw new Error(errors.join('\n'))
  } finally {
    if (application) await application.close()
    if (profile.startsWith(resolve(root, '.ui-review-'))) rmSync(profile, { recursive: true, force: true, maxRetries: 5, retryDelay: 250 })
  }
}
run().catch(error => { console.error(error); process.exitCode = 1 })
